@extends('layouts.app')
@section('title','Caja')
@section('content')
<div class="space-y-6">
<div class="flex items-center justify-between"><div><h2 class="text-2xl font-semibold text-slate-800">Caja</h2><p class="text-sm text-slate-600">Consulta la sesión abierta y tus aperturas recientes.</p></div><a href="{{ route('dashboard') }}" class="rounded-lg border border-slate-300 px-4 py-2">Volver</a></div>
@foreach(['success'=>'green','info'=>'amber'] as $key=>$color)@if(session($key))<div class="rounded-lg border border-{{ $color }}-200 bg-{{ $color }}-50 p-4 text-{{ $color }}-800">{{ session($key) }}</div>@endif @endforeach
<div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-800">El POS todavía permite cobrar sin apertura durante esta etapa.</div>
@if($openSessions->isEmpty())
<x-card><div class="py-8 text-center"><h3 class="text-xl font-semibold">No hay una caja abierta para este usuario.</h3>@if($defaultRegister)<p class="mt-2 text-slate-600">Caja sugerida: {{ $defaultRegister->name }}</p>@endif @can('caja.abrir')<a href="{{ route('cash.open.create') }}" class="mt-6 inline-block rounded-xl bg-amber-500 px-8 py-4 font-bold text-white hover:bg-amber-600">Abrir caja</a>@endcan</div></x-card>
@else
@foreach($openSessions as $session)<x-card><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><span class="text-xs uppercase text-slate-500">Número</span><strong class="block text-xl">{{ $session->session_number }}</strong></div><div><span class="text-xs uppercase text-slate-500">Caja física</span><strong class="block">{{ $session->cashRegister->name }}</strong></div><div><span class="text-xs uppercase text-slate-500">Sucursal</span><strong class="block">{{ $session->branch->name }}</strong></div><div><span class="text-xs uppercase text-slate-500">Estado</span><strong class="block text-green-700">Abierta</strong></div><div><span class="text-xs uppercase text-slate-500">Cajero</span><strong class="block">{{ $session->openedBy->name }}</strong></div><div><span class="text-xs uppercase text-slate-500">Apertura</span><strong class="block">{{ $session->opened_at->timezone($companyTimezone)->format('d/m/Y H:i') }}</strong></div><div><span class="text-xs uppercase text-slate-500">Fondo inicial CRC</span><strong class="block text-xl">₡{{ number_format((float)$session->opening_amount,0,',','.') }}</strong></div>@if($session->accepts_usd_snapshot)<div><span class="text-xs uppercase text-slate-500">USD</span><strong class="block">USD 1 = ₡{{ number_format((float)$session->usd_exchange_rate,2,',','.') }} · ${{ number_format((float)$session->opening_amount_usd,2,',','.') }}</strong><small>{{ $session->exchangeRateEnteredBy?->name }}</small></div>@endif</div>@php($canViewMovements=auth()->user()->hasPermission('caja.ver',$session->company)&&($session->opened_by===auth()->id()||auth()->user()->hasPermission('caja.ver_todas',$session->company))) @php($canCreateMovement=auth()->user()->hasPermission('caja.movimientos',$session->company)&&($settings->session_mode==='shared'||$session->opened_by===auth()->id())) @if($canViewMovements||$canCreateMovement)<div class="mt-5 flex flex-wrap justify-end gap-2">@if($canViewMovements)<a href="{{ route('cash.movements.index',$session) }}" class="rounded-xl bg-amber-500 px-4 py-3 font-normal text-black hover:bg-amber-600">Ver movimientos</a>@endif @if($canCreateMovement)<a href="{{ route('cash.movements.create',$session) }}" class="rounded-xl bg-amber-500 px-4 py-3 font-normal text-black hover:bg-amber-600">Registrar movimiento</a>@endif</div>@endif</x-card>@endforeach
@endif
<x-card><x-slot:header><h3 class="text-lg font-semibold">Últimas sesiones</h3></x-slot:header><div class="overflow-x-auto"><table class="min-w-full"><thead class="border-b bg-slate-100"><tr><th class="px-4 py-3 text-left">Número</th><th class="px-4 py-3 text-left">Caja</th><th class="px-4 py-3 text-left">Usuario</th><th class="px-4 py-3 text-left">Apertura</th><th class="px-4 py-3 text-right">Fondo</th><th class="px-4 py-3 text-center">Estado</th></tr></thead><tbody>@forelse($history as $session)<tr class="border-b"><td class="px-4 py-3">{{ $session->session_number }}</td><td class="px-4 py-3">{{ $session->cashRegister->name }}</td><td class="px-4 py-3">{{ $session->openedBy->name }}</td><td class="px-4 py-3">{{ $session->opened_at->timezone($companyTimezone)->format('d/m/Y H:i') }}</td><td class="px-4 py-3 text-right">₡{{ number_format((float)$session->opening_amount,0,',','.') }}</td><td class="px-4 py-3 text-center">{{ $session->status==='open'?'Abierta':ucfirst($session->status) }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No hay sesiones registradas.</td></tr>@endforelse</tbody></table></div></x-card>
</div>
@endsection
