@extends('layouts.app')
@section('title','Abrir caja')
@section('content')
<div class="mx-auto max-w-4xl" x-data="{ processing:false, opening:'{{ old('opening_amount',0) }}' }"><div class="mb-6 flex items-center justify-between"><div><h2 class="text-2xl font-semibold">Abrir caja</h2><p class="text-sm text-slate-600">Registra el fondo inicial contado.</p></div><a href="{{ route('cash.index') }}" class="rounded-lg border border-slate-300 px-4 py-2">Volver</a></div>
@if($registers->isEmpty())<x-card><div class="py-8 text-center"><p class="text-lg font-semibold">No existen cajas activas en esta sucursal.</p>@if($canManageRegisters)<a href="{{ route('settings.cash-registers.index') }}" class="mt-5 inline-block rounded-xl bg-amber-500 px-5 py-3 font-semibold text-white">Configurar cajas</a>@endif</div></x-card>@else
<x-card><form method="POST" action="{{ route('cash.open.store') }}" @submit="processing=true">@csrf
@if($errors->any())<div class="mb-5 rounded-lg bg-red-50 p-4 text-red-700">{{ $errors->first() }}</div>@endif
<div class="space-y-6"><div><label class="mb-2 block font-medium">Caja física</label><select name="cash_register_id" required class="w-full rounded-xl border-slate-300 px-4 py-3">@foreach($registers as $register)<option value="{{ $register->id }}" @selected((int)old('cash_register_id',$selectedRegisterId)===$register->id)>{{ $register->name }}{{ $register->is_default?' — Predeterminada':'' }}</option>@endforeach</select></div>
<div><label class="mb-2 block font-medium">Fondo inicial en colones</label><input name="opening_amount" x-model="opening" type="number" min="0" step="1" required class="w-full rounded-xl border-slate-300 px-4 py-3 text-right text-2xl font-bold"><div class="mt-3 rounded-xl bg-slate-900 p-5 text-right text-white"><span class="text-sm text-slate-400">Fondo inicial</span><strong class="block text-4xl" x-text="new Intl.NumberFormat('es-CR',{style:'currency',currency:'CRC',maximumFractionDigits:0}).format(Number(opening)||0)"></strong></div></div>
@if($settings->accepts_usd)<div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block font-medium">Tipo de cambio: USD 1 = ₡</label><input name="usd_exchange_rate" type="number" min="0.0001" step="0.0001" required class="w-full rounded-xl border-slate-300 px-4 py-3">@if($settings->usd_exchange_rate_min||$settings->usd_exchange_rate_max)<p class="mt-1 text-sm text-slate-500">Rango: {{ $settings->usd_exchange_rate_min??'sin mínimo' }} – {{ $settings->usd_exchange_rate_max??'sin máximo' }}</p>@endif</div><div><label class="mb-2 block font-medium">Fondo inicial en dólares</label><input name="opening_amount_usd" type="number" min="0" step="0.01" value="{{ old('opening_amount_usd',0) }}" class="w-full rounded-xl border-slate-300 px-4 py-3"></div></div><p class="text-sm text-slate-500">El tipo de cambio quedará fijo para esta sesión y será registrado por {{ $cashier->name }}.</p>@endif
<label class="flex gap-3"><input name="confirmation" value="1" type="checkbox" required class="mt-1 rounded text-amber-500"><span>Confirmo que el fondo inicial contado es correcto.</span></label></div>
<div class="mt-8 flex justify-end gap-3"><a href="{{ route('cash.index') }}" class="rounded-xl border border-slate-300 px-6 py-3">Cancelar</a><button :disabled="processing" class="rounded-xl bg-amber-500 px-6 py-3 font-bold text-white hover:bg-amber-600 disabled:opacity-50" x-text="processing?'Abriendo…':'Abrir caja'"></button></div></form></x-card>@endif</div>
@endsection
