@extends('layouts.app')
@section('title', 'Revisar inventario P36')
@section('content')
@php $errorCount = collect($rows)->where('valid', false)->count(); @endphp
<div class="mx-auto max-w-7xl space-y-6" data-inventory-migration-preview>
    <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-wide text-cyan-700">P36 · Vista previa</p><h1 class="mt-1 text-2xl font-bold text-slate-800">Conciliar inventario</h1><p class="mt-2 text-sm text-slate-600">Origen: <strong>{{ $rows[0]['source_key'] ?? '—' }}</strong>. Aún no se modificó stock ni Kardex.</p></div><a href="{{ route('importaciones.inventario-migracion') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Cargar otro archivo</a></header>
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><div class="rounded-xl border bg-white p-4 text-sm">Filas<strong class="block text-2xl">{{ count($rows) }}</strong></div><div class="rounded-xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-cyan-700">Saldos iniciales<strong class="block text-2xl">{{ collect($rows)->where('record_type', 'initial_balance')->count() }}</strong></div><div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Con errores<strong class="block text-2xl">{{ $errorCount }}</strong></div></div>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[1100px] w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-600"><tr><th class="px-4 py-3">Fila / clave</th><th class="px-4 py-3">Tipo / fecha</th><th class="px-4 py-3">Sucursal</th><th class="px-4 py-3">Producto</th><th class="px-4 py-3 text-right">Cantidad</th><th class="px-4 py-3 text-right">Actual / anterior / nuevo</th><th class="px-4 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($rows as $row)<tr class="align-top {{ $row['valid'] ? '' : 'bg-red-50/50' }}"><td class="px-4 py-3"><strong>{{ $row['row_number'] }}</strong><br>{{ $row['row_key'] ?: '—' }}</td><td class="px-4 py-3">{{ $row['record_type'] === 'initial_balance' ? 'Saldo inicial' : 'Movimiento histórico' }}<br>{{ $row['occurred_at'] ?: '—' }}</td><td class="px-4 py-3">{{ $row['branch_code'] ?: '—' }}</td><td class="px-4 py-3">{{ $row['product_code'] ?: $row['barcode'] ?: '—' }}<br>{{ $row['product_name'] ?: '—' }}</td><td class="px-4 py-3 text-right">{{ $row['quantity'] ?? '—' }}</td><td class="px-4 py-3 text-right">{{ $row['current_stock'] ?? '—' }} / {{ $row['previous_stock'] ?? '—' }} / {{ $row['new_stock'] ?? '—' }}</td><td class="px-4 py-3">@if($row['valid'])<span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">Lista</span>@else<span class="rounded-full bg-red-100 px-3 py-1 text-xs font-semibold text-red-700">Error</span><ul class="mt-2 space-y-1 text-xs text-red-700">@foreach($row['errors'] as $error)<li><strong>{{ $error['field'] }}:</strong> {{ $error['message'] }}</li>@endforeach</ul>@endif</td></tr>@endforeach</tbody></table></div></section>
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p class="text-sm text-slate-600">La confirmación revalida el lote y ejecuta todas las filas en una transacción.</p>@if($errorCount === 0)<form action="{{ route('importaciones.inventario-migracion.import') }}" method="POST" onsubmit="return confirm('¿Confirmar la migración P36?');">@csrf<button class="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-cyan-700 px-5 py-3 text-sm font-bold text-white sm:w-auto">Confirmar migración</button></form>@else<p class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">Corrija todas las filas antes de confirmar.</p>@endif</div>
</div>
@endsection
