@extends('layouts.app')

@section('title', 'Revisar ventas históricas')

@section('content')
@php
    $validCount = collect($rows)->where('valid', true)->count();
    $errorCount = collect($rows)->where('valid', false)->count();
    $documentCount = collect($rows)->pluck('sale_number')->filter()->unique()->count();
@endphp
<div class="mx-auto max-w-7xl space-y-6" data-historical-sale-preview>
    <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-wide text-violet-700">P34/P35 · Vista previa</p><h1 class="mt-1 text-2xl font-bold text-slate-800">Revisar ventas históricas</h1><p class="mt-2 text-sm text-slate-600">Aún no se ha escrito ningún encabezado ni línea.</p></div><a href="{{ route('importaciones.ventas-historicas') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Cargar otro archivo</a></header>
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><div class="rounded-xl border bg-white p-4 text-sm">Documentos<strong class="block text-2xl">{{ $documentCount }}</strong></div><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">Líneas listas<strong class="block text-2xl">{{ $validCount }}</strong></div><div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Con errores<strong class="block text-2xl">{{ $errorCount }}</strong></div></div>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[1100px] w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-600"><tr><th class="px-4 py-3">Fila / documento</th><th class="px-4 py-3">Fecha / sucursal</th><th class="px-4 py-3">Cliente</th><th class="px-4 py-3">Producto</th><th class="px-4 py-3 text-right">Cantidad / precio</th><th class="px-4 py-3 text-right">Total línea</th><th class="px-4 py-3">Estado</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($rows as $row)<tr class="align-top {{ $row['valid'] ? '' : 'bg-red-50/50' }}"><td class="px-4 py-3"><strong>{{ $row['row_number'] }}</strong><br>{{ $row['sale_number'] ?: '—' }} · #{{ $row['line_number'] ?: '—' }}</td><td class="px-4 py-3">{{ $row['completed_at'] ?: '—' }}<br>{{ $row['branch_code'] ?: '—' }}</td><td class="px-4 py-3">{{ $row['customer_identification'] ?: 'Consumidor final' }}</td><td class="px-4 py-3">{{ $row['product_code'] ?: $row['barcode'] ?: '—' }}<br>{{ $row['description'] ?: '—' }}</td><td class="px-4 py-3 text-right">{{ $row['quantity'] ?? '—' }} / {{ $row['unit_price'] ?? '—' }}</td><td class="px-4 py-3 text-right">{{ $row['line_total'] ?? '—' }}</td><td class="px-4 py-3">@if($row['valid'])<span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">Lista</span>@else<span class="rounded-full bg-red-100 px-3 py-1 text-xs font-semibold text-red-700">Error</span><ul class="mt-2 space-y-1 text-xs text-red-700">@foreach($row['errors'] as $error)<li><strong>{{ $error['field'] }}:</strong> {{ $error['message'] }}</li>@endforeach</ul>@endif</td></tr>@endforeach</tbody></table></div></section>
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p class="text-sm text-slate-600">La confirmación revalida y usa una sola transacción sin servicios operativos del POS.</p>@if($errorCount === 0 && count($rows) > 0)<form action="{{ route('importaciones.ventas-historicas.import') }}" method="POST" onsubmit="return confirm('¿Confirmar {{ $documentCount }} documentos históricos?');">@csrf<button class="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-violet-700 px-5 py-3 text-sm font-bold text-white sm:w-auto">Confirmar importación</button></form>@else<p class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">Corrija todos los documentos antes de confirmar.</p>@endif</div>
</div>
@endsection
