<?php
namespace Tests\Feature;
use App\Models\{Branch,CashRegister,CashSession,Company,Customer,Layaway,LayawayAlert,PaymentMethod,Permission,Product,ProductCategory,Role,Sale,Unit,User}; use App\Notifications\LayawayUpcomingNotification; use App\Services\PaymentMethodProvisioner; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\{DB,Notification}; use Tests\TestCase;
class LayawayV1Test extends TestCase {use RefreshDatabase;
 public function test_creation_reserves_inventory_and_registers_initial_payment():void{[$c,$b,$u,$s,$m,$p,$customer]=$this->context();$this->actingAs($u)->withSession($this->ctx($c,$b))->post(route('apartados.store'),['customer_id'=>$customer->id,'items'=>[['product_id'=>$p->id,'quantity'=>6]],'initial_amount'=>200,'payment_method_id'=>$m->id,'cash_session_id'=>$s->id])->assertSessionHasErrors('items');$this->createLayaway($u,$c,$b,$s,$m,$p,$customer,200)->assertRedirect();$a=Layaway::firstOrFail();$this->assertSame('1800.0000',$a->balance_due);$this->assertSame('active',$a->status);$this->assertSame(3.0,(float)DB::table('branch_product')->value('stock'));$this->assertDatabaseHas('inventory_movements',['type'=>'layaway_reserve','reference_id'=>$a->id]);$this->assertDatabaseHas('layaway_payments',['amount'=>200]);$this->assertSame(200.0,app(\App\Services\Cash\CashExpectedAmountService::class)->calculate($s));}
 public function test_partial_and_total_payments_update_balance_and_block_overpayment():void{[$c,$b,$u,$s,$m,$p,$customer]=$this->context();$this->createLayaway($u,$c,$b,$s,$m,$p,$customer,200);$a=Layaway::firstOrFail();$this->pay($u,$c,$b,$a,$s,$m,300)->assertRedirect();$this->assertSame('1500.0000',$a->fresh()->balance_due);$this->pay($u,$c,$b,$a,$s,$m,1600)->assertSessionHasErrors('amount');$this->pay($u,$c,$b,$a,$s,$m,1500)->assertRedirect();$this->assertSame('paid',$a->fresh()->status);$this->pay($u,$c,$b,$a,$s,$m,1)->assertSessionHasErrors('layaway');}
 public function test_cancellation_releases_inventory_and_blocks_further_operations():void{[$c,$b,$u,$s,$m,$p,$customer]=$this->context();$this->createLayaway($u,$c,$b,$s,$m,$p,$customer,200);$a=Layaway::firstOrFail();$this->actingAs($u)->withSession($this->ctx($c,$b))->post(route('apartados.cancel',$a),['reason'=>'Cliente desistió'])->assertRedirect();$this->assertSame('cancelled',$a->fresh()->status);$this->assertSame(5.0,(float)DB::table('branch_product')->value('stock'));$this->pay($u,$c,$b,$a,$s,$m,1)->assertSessionHasErrors('layaway');}
 public function test_scheduled_expiration_releases_inventory_and_is_idempotent():void{[$c,$b,$u,$s,$m,$p,$customer]=$this->context();$this->createLayaway($u,$c,$b,$s,$m,$p,$customer,200);$a=Layaway::firstOrFail();$a->update(['expires_at'=>today()->subDay()]);$this->artisan('layaways:process')->assertSuccessful();$this->assertSame('expired',$a->fresh()->status);$this->assertSame(5.0,(float)DB::table('branch_product')->value('stock'));$this->artisan('layaways:process')->assertSuccessful();$this->assertSame(5.0,(float)DB::table('branch_product')->value('stock'));}
 public function test_delivery_requires_full_payment_creates_sale_without_double_inventory_deduction():void{[$c,$b,$u,$s,$m,$p,$customer]=$this->context();$this->createLayaway($u,$c,$b,$s,$m,$p,$customer,200);$a=Layaway::firstOrFail();$this->actingAs($u)->withSession($this->ctx($c,$b))->post(route('apartados.deliver',$a))->assertSessionHasErrors('layaway');$this->pay($u,$c,$b,$a,$s,$m,1800);$this->actingAs($u)->withSession($this->ctx($c,$b))->post(route('apartados.deliver',$a))->assertRedirect();$this->assertSame('delivered',$a->fresh()->status);$this->assertNotNull($a->fresh()->delivered_sale_id);$this->assertSame(Sale::STATUS_COMPLETED,$a->fresh()->sale->status);$this->assertSame(3.0,(float)DB::table('branch_product')->value('stock'));}
 public function test_permissions_and_company_branch_isolation():void{[$c,$b,$u,$s,$m,$p,$customer]=$this->context();$this->createLayaway($u,$c,$b,$s,$m,$p,$customer,200);$a=Layaway::firstOrFail();[$c2,$b2,$u2]=$this->context('Otra');$this->actingAs($u2)->withSession($this->ctx($c2,$b2))->get(route('apartados.show',$a))->assertNotFound();$plain=User::factory()->create();$plain->companies()->attach($c->id);$plain->branches()->attach($b->id);$this->actingAs($plain)->withSession($this->ctx($c,$b))->get(route('apartados.index'))->assertForbidden();}
 public function test_upcoming_alert_and_dashboard_summary():void{Notification::fake();[$c,$b,$u,$s,$m,$p,$customer]=$this->context();$this->createLayaway($u,$c,$b,$s,$m,$p,$customer,200);$a=Layaway::firstOrFail();$a->update(['expires_at'=>today()->addDays(3)]);$this->artisan('layaways:process')->assertSuccessful();$this->assertDatabaseHas('layaway_alerts',['layaway_id'=>$a->id,'type'=>'upcoming']);Notification::assertSentTo($u,LayawayUpcomingNotification::class);$this->actingAs($u)->withSession($this->ctx($c,$b))->get(route('dashboard'))->assertOk()->assertSee('Apartados')->assertSee('Monto pendiente');}
 private function context(array|string $permissions=['apartados.ver','apartados.crear','apartados.abonar','apartados.cancelar','apartados.entregar','dashboard.ver']):array{$name=is_string($permissions)?$permissions:'Empresa';if(is_string($permissions))$permissions=['apartados.ver'];$c=Company::create(['trade_name'=>$name.uniqid(),'currency'=>'CRC','timezone'=>'America/Costa_Rica','layaway_validity_days'=>30,'layaway_alert_days'=>5,'is_active'=>true]);$b=Branch::create(['company_id'=>$c->id,'name'=>'Principal','code'=>'P'.uniqid(),'is_active'=>true]);$u=User::factory()->create();$r=Role::create(['company_id'=>$c->id,'name'=>'R'.uniqid(),'is_active'=>true]);foreach($permissions as $n){$perm=Permission::firstOrCreate(['name'=>$n],['label'=>$n,'module'=>'Test','is_active'=>true]);$r->permissions()->attach($perm);}$u->companies()->attach($c->id,['role_id'=>$r->id]);$u->branches()->attach($b->id);app(PaymentMethodProvisioner::class)->provision($c);$m=PaymentMethod::forCompany($c->id)->where('type','cash')->firstOrFail();$register=CashRegister::create(['company_id'=>$c->id,'branch_id'=>$b->id,'code'=>'C'.uniqid(),'name'=>'Caja','is_active'=>true]);$s=CashSession::create(['company_id'=>$c->id,'branch_id'=>$b->id,'cash_register_id'=>$register->id,'session_number'=>'CAJA-'.uniqid(),'opened_by'=>$u->id,'status'=>'open','open_guard'=>'OPEN','opening_amount'=>0,'opened_at'=>now()]);$id=uniqid();$cat=ProductCategory::create(['company_id'=>$c->id,'name'=>'C'.$id,'slug'=>'c'.$id,'is_active'=>true]);$unit=Unit::create(['company_id'=>$c->id,'name'=>'Unidad','abbreviation'=>'U','slug'=>'u'.$id,'is_active'=>true]);$p=Product::create(['company_id'=>$c->id,'category_id'=>$cat->id,'unit_id'=>$unit->id,'name'=>'Producto','internal_code'=>'P'.$id,'cost'=>500,'sale_price'=>1000,'tax_rate'=>0,'track_inventory'=>true,'is_active'=>true]);DB::table('branch_product')->insert(['branch_id'=>$b->id,'product_id'=>$p->id,'stock'=>5,'created_at'=>now(),'updated_at'=>now()]);$customer=Customer::create(['company_id'=>$c->id,'name'=>'Cliente','customer_type'=>'individual','credit_limit'=>0,'is_active'=>true]);return[$c,$b,$u,$s,$m,$p,$customer];}
 private function createLayaway($u,$c,$b,$s,$m,$p,$customer,$amount){return$this->actingAs($u)->withSession($this->ctx($c,$b))->post(route('apartados.store'),['customer_id'=>$customer->id,'items'=>[['product_id'=>$p->id,'quantity'=>2]],'initial_amount'=>$amount,'payment_method_id'=>$m->id,'cash_session_id'=>$s->id]);}
 private function pay($u,$c,$b,$a,$s,$m,$amount){return$this->actingAs($u)->withSession($this->ctx($c,$b))->post(route('apartados.payments.store',$a),['amount'=>$amount,'payment_method_id'=>$m->id,'cash_session_id'=>$s->id]);} private function ctx($c,$b):array{return['active_company_id'=>$c->id,'active_branch_id'=>$b->id];}
}
