@extends('layouts.app') @section('title','Detalle de apartado') @section('content')
@php($labels=['active'=>'Activo','paid'=>'Pagado','delivered'=>'Entregado','expired'=>'Vencido','cancelled'=>'Cancelado'])
<div class="space-y-5"><div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-2xl font-bold">{{$layaway->number}}</h1><p class="text-sm text-slate-500">{{$layaway->customer->name}}</p></div><a href="{{route('apartados.index')}}" class="rounded border px-4 py-2">Volver</a></div>
<x-card><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div>Estado<br><strong>{{$labels[$layaway->status]}}</strong></div><div>Total<br><strong>₡{{number_format((float)$layaway->total,0,',','.')}}</strong></div><div>Abonado<br><strong>₡{{number_format((float)$layaway->paid_total,0,',','.')}}</strong></div><div>Saldo<br><strong>₡{{number_format((float)$layaway->balance_due,0,',','.')}}</strong></div><div>Vencimiento<br><strong>{{$layaway->expires_at->format('d/m/Y')}}</strong></div></div></x-card>
<x-card><h2 class="mb-3 font-semibold">Productos reservados</h2><div class="overflow-x-auto"><table class="w-full min-w-[600px] text-sm"><thead><tr><th class="p-2 text-left">Producto</th><th class="p-2 text-right">Cantidad</th><th class="p-2 text-right">Precio</th><th class="p-2 text-right">Total</th></tr></thead><tbody>@foreach($layaway->items as $i)<tr class="border-t"><td class="p-2">{{$i->description}}</td><td class="p-2 text-right">{{number_format((float)$i->quantity,$i->product?->unit?->allows_decimals?4:0,',','.')}}</td><td class="p-2 text-right">₡{{number_format((float)$i->unit_price,0,',','.')}}</td><td class="p-2 text-right">₡{{number_format((float)$i->total,0,',','.')}}</td></tr>@endforeach</tbody></table></div></x-card>
@can('apartados.abonar')@if($layaway->status==='active'&&!$layaway->expires_at->isBefore(today()))<x-card><h2 class="mb-3 font-semibold">Registrar abono</h2><form method="POST" action="{{route('apartados.payments.store',$layaway)}}" class="grid gap-3 md:grid-cols-5">@csrf<input required type="number" min="1" max="{{$layaway->balance_due}}" step="1" name="amount" placeholder="Monto" class="rounded border-slate-300"><select required name="payment_method_id" class="rounded border-slate-300">@foreach($methods as $m)<option value="{{$m->id}}">{{$m->name}}</option>@endforeach</select><select name="cash_session_id" class="rounded border-slate-300"><option value="">Sesión de caja</option>@foreach($sessions as $s)<option value="{{$s->id}}">{{$s->session_number}} — {{$s->cashRegister->name}}</option>@endforeach</select><input name="reference" placeholder="Referencia" class="rounded border-slate-300"><input name="payment_notes" placeholder="Notas" class="rounded border-slate-300"><button class="rounded bg-amber-500 px-4 py-2 font-semibold text-white md:col-span-5 md:w-fit">Registrar abono</button></form></x-card>@endif @endcan
<x-card><h2 class="mb-3 font-semibold">Historial de abonos</h2><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-sm"><thead><tr><th class="p-2 text-left">Fecha</th><th class="p-2">Método</th><th class="p-2">Referencia</th><th class="p-2">Usuario</th><th class="p-2 text-right">Monto</th></tr></thead><tbody>@foreach($layaway->payments as $p)<tr class="border-t"><td class="p-2">{{$p->paid_at->format('d/m/Y H:i')}}</td><td class="p-2 text-center">{{$p->paymentMethod->name}}</td><td class="p-2 text-center">{{$p->reference??'—'}}</td><td class="p-2 text-center">{{$p->user->name}}</td><td class="p-2 text-right">₡{{number_format((float)$p->amount,0,',','.')}}</td></tr>@endforeach</tbody></table></div></x-card>
<div class="flex flex-wrap gap-3">@can('apartados.entregar')@if($layaway->status==='paid')<form method="POST" action="{{route('apartados.deliver',$layaway)}}">@csrf<button class="rounded bg-emerald-600 px-4 py-2 font-semibold text-white">Entregar y completar venta</button></form>@endif @endcan @can('apartados.cancelar')@if(in_array($layaway->status,['active','paid']))<form method="POST" action="{{route('apartados.cancel',$layaway)}}" class="flex gap-2">@csrf<input required minlength="3" name="reason" placeholder="Motivo de cancelación" class="rounded border-slate-300"><button class="rounded bg-red-600 px-4 py-2 font-semibold text-white">Cancelar</button></form>@endif @endcan @if($layaway->sale)<a href="{{route('ventas.show',$layaway->sale)}}" class="rounded bg-slate-900 px-4 py-2 text-white">Ver venta</a>@endif</div>
@if($errors->any())<p class="rounded bg-red-50 p-3 text-red-700">{{$errors->first()}}</p>@endif</div>@endsection
