const assert = require('node:assert/strict');
const vm = require('node:vm');
const html = require('node:fs').readFileSync(0, 'utf8');
const script = [...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]).find(s => s.includes("Alpine.data('posTerminal'"));
assert.ok(script);
let factory;
vm.runInNewContext(script, { document: { addEventListener: (_, fn) => fn() }, Alpine: { data: (_, fn) => { factory = fn; } }, console });
const pos = factory();
pos.$nextTick = () => {};
pos.$refs = {};
pos.cart = [{ id: 1, quantity: 1, sale_price: 8000, tax_rate: 0, _discount: 0, _unitPrice: '' }];
const cash = pos.paymentMethods.find(m => m.type === 'cash');
pos.checkout.draft = { methodId: cash.id, amount: '8000', receivedAmount: '0', receivedUsd: '20', reference: '' };
assert.equal(pos.usdCashEnabled, true);
assert.equal(pos.usdDraft.equivalent, '10100.0000');
assert.equal(pos.usdDraft.changeCrc, '2100.0000');
pos.usdSession.policy = 'usd_only';
assert.equal(pos.usdDraft.changeUsd, '4.1584');
pos.usdSession.policy = 'either';
assert.equal(pos.usdDraft.valid, false);
pos.checkout.draft.changeCurrency = 'USD';
assert.equal(pos.usdDraft.valid, true);
pos.checkout.draft.receivedUsd = 'NaN';
assert.equal(pos.usdDraft, null);
pos.checkout.draft.receivedUsd = '10';
pos.checkout.draft.receivedAmount = '2950';
assert.equal(pos.usdDraft.covered, '8000.0000');
assert.equal(pos.usdDraft.hasChange, false);
pos.usdSession.enabled = false;
assert.equal(pos.usdCashEnabled, false);
assert.equal(pos.paymentMethods.some(m => m.type === 'loyalty_points'), false);
assert.ok(pos.loyaltyBlockedReason.includes('Seleccione un cliente'));
pos.selectedCustomer = {id: 1};
Object.assign(pos.loyalty, {available: true, eligible: false, offers_allowed: true, max_redeemable_points: '100', requested: '50'});
assert.equal(pos.loyaltyRequestedPoints, 0);
assert.ok(pos.loyaltyBlockedReason.includes('mínimo'));
pos.loyalty.eligible = true;
pos.loyalty.offers_allowed = false;
assert.equal(pos.loyaltyRequestedPoints, 0);
assert.ok(pos.loyaltyBlockedReason.includes('ofertas'));
console.log('USD UI OK');
