<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vista previa de etiquetas</title>
<style>
:root{--label-width:{{ explode('x',$size)[0] }}mm;--label-height:{{ explode('x',$size)[1] }}mm}*{box-sizing:border-box}body{margin:0;background:#e2e8f0;font-family:Arial,sans-serif;color:#0f172a}.toolbar{position:sticky;top:0;z-index:2;display:flex;gap:12px;align-items:center;justify-content:space-between;padding:12px;background:#fff;border-bottom:1px solid #cbd5e1}.toolbar button{min-height:44px;border:0;border-radius:10px;background:#4f46e5;color:white;padding:0 18px;font-weight:700}.sheet{display:grid;grid-template-columns:repeat(auto-fill,var(--label-width));gap:3mm;justify-content:center;padding:5mm}.label{width:var(--label-width);height:var(--label-height);overflow:hidden;background:#fff;border:1px dashed #94a3b8;padding:2mm;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.name{max-width:100%;font-size:10pt;font-weight:700;line-height:1.1}.price{font-size:15pt;font-weight:900}.barcode{width:100%;margin-top:1mm}.label-barcode{display:block;width:100%;height:9mm}.code{font-size:7pt;letter-spacing:.08em}.barcode_large .label-barcode{height:14mm}.price_large .price{font-size:24pt}.sku .code{font-size:16pt;font-weight:800}.meta{font-size:12px;color:#475569}@media(max-width:767px){.toolbar{align-items:flex-start;flex-direction:column}.sheet{justify-content:start;overflow-x:auto}}@media print{body{background:#fff}.toolbar{display:none}.sheet{padding:0;gap:0;justify-content:start}.label{border:0;break-inside:avoid}}
</style></head><body>
<div class="toolbar"><div><strong>{{ $labels->count() }} etiquetas · {{ $size }}</strong><div class="meta">Destino: {{ collect($setting?->print_destinations ?? [])->map(fn($d)=>$d==='cashier'?'Cajero':'Administrador')->join(' y ') ?: 'Sin configurar' }}</div></div><button onclick="window.print()">Imprimir</button></div>
<main class="sheet" data-responsive="360 768 1280">@foreach($labels as $label)<article class="label {{ $template }}">
@if(in_array($template,['name_price','name_price_barcode','custom_simple']))<div class="name">{{ $template==='custom_simple' && $setting?->custom_heading ? $setting->custom_heading.' · ' : '' }}{{ $label['product']->name }}</div>@endif
@if(in_array($template,['name_price','name_price_barcode','price_large','custom_simple']))<div class="price">₡{{ number_format($label['product']->sale_price,2,',','.') }}</div>@endif
@if(in_array($template,['name_price_barcode','barcode_large']) && $label['barcode_svg'])<div class="barcode">{!! $label['barcode_svg'] !!}<div class="code">{{ $label['barcode'] }}</div></div>@elseif($template==='sku')<div class="code">{{ $label['product']->internal_code }}</div>@elseif(in_array($template,['name_price_barcode','barcode_large']))<div class="code">Sin código de barras</div>@endif
</article>@endforeach</main></body></html>
