@extends('layouts.app')
@section('title', 'Cotización '.$quote->quote_number)
@section('content')
<div class="space-y-5">
    @if(session('success'))<div class="rounded bg-green-50 p-3 text-green-800">{{ session('success') }}</div>@endif
    <div class="rounded-lg border-2 border-slate-800 p-3 text-center font-bold">NO ES COMPROBANTE FISCAL</div>
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold">{{ $quote->quote_number }}</h1><p>{{ $quote->customer?->name ?? 'Consumidor Final' }} · {{ $quote->branch->name }}</p></div><div class="flex gap-2"><a href="{{ route('cotizaciones.print', $quote) }}" target="_blank" class="rounded border px-4 py-2">Imprimir</a>@can('cotizaciones.crear')@if($quote->effective_status === 'active')<a href="{{ route('pos.index', ['quote_id'=>$quote->id]) }}" class="rounded bg-slate-900 px-4 py-2 text-white">Convertir en venta</a>@endif @endcan</div></div>
    <x-card><p><strong>Estado:</strong> {{ $quote->status_label }}</p><p><strong>Fecha:</strong> {{ $quote->created_at->format('d/m/Y H:i') }}</p><p><strong>Vence:</strong> {{ $quote->expires_at?->format('d/m/Y') ?? 'Sin vencimiento' }}</p>@if($quote->notes)<p><strong>Notas:</strong> {{ $quote->notes }}</p>@endif @if($quote->convertedSale)<p><strong>Venta:</strong> <a class="underline" href="{{ route('ventas.show',$quote->convertedSale) }}">{{ $quote->convertedSale->sale_number }}</a></p>@endif @if($quote->cancellation_reason)<p><strong>Anulación:</strong> {{ $quote->cancellation_reason }}</p>@endif</x-card>
    <x-card><table class="min-w-full"><thead><tr><th class="p-2 text-left">Producto</th><th class="p-2 text-right">Cantidad</th><th class="p-2 text-right">Precio</th><th class="p-2 text-right">Descuento</th><th class="p-2 text-right">Total</th></tr></thead><tbody>@foreach($quote->items as $item)<tr><td class="p-2">{{ $item->description }}<br><small>{{ $item->product_code }}</small></td><td class="p-2 text-right">{{ $item->quantity }}</td><td class="p-2 text-right">{{ $item->unit_price }}</td><td class="p-2 text-right">{{ $item->discount_total }}</td><td class="p-2 text-right">{{ $item->total }}</td></tr>@endforeach</tbody></table><div class="mt-4 text-right text-xl font-bold">Total: ₡{{ number_format((float)$quote->total,2,',','.') }}</div></x-card>
    @can('cotizaciones.editar')@if($quote->status === 'active')<form method="POST" action="{{ route('cotizaciones.cancel',$quote) }}" class="flex gap-2">@csrf<input required minlength="3" maxlength="255" name="cancellation_reason" placeholder="Motivo de cancelación" class="rounded border px-3"><button class="rounded bg-red-600 px-4 py-2 text-white">Cancelar cotización</button></form>@endif @endcan
</div>
@endsection
