@extends('layouts.app')
@section('title', 'Premios de Fidelización')
@section('content')
<div class="space-y-6">
<div><h1 class="text-2xl font-semibold text-slate-800">Premios</h1><p class="text-sm text-slate-500">Premios directos canjeables con puntos. Costo y cupo admiten hasta cuatro decimales. Cada canje consume 1 unidad del premio o producto.</p></div>
@if(session('success'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
@php $modeLabels = ['unlimited' => 'Ilimitado', 'limited' => 'Cupo propio', 'product' => 'Producto real']; @endphp
<x-card><x-slot:header><h2 class="text-lg font-semibold">Nuevo premio</h2></x-slot:header>
<form method="POST" action="{{ route('loyalty.rewards.store') }}" x-data="{ mode: @js(old('availability_mode', 'unlimited')) }" class="grid gap-4 md:grid-cols-2">@csrf
<x-input name="name" label="Nombre" :value="old('name')" required/>
<div><label for="type" class="form-label">Tipo<span class="text-red-500">*</span></label><select name="type" id="type" class="form-input">@foreach($types as $type)<option value="{{ $type }}" @selected(old('type') === $type)>{{ ['product' => 'Producto', 'discount' => 'Descuento', 'service' => 'Servicio', 'gift' => 'Regalo'][$type] }}</option>@endforeach</select>@error('type')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div><label for="availability_mode" class="form-label">Disponibilidad<span class="text-red-500">*</span></label><select name="availability_mode" id="availability_mode" x-model="mode" class="form-input">@foreach($modes as $mode)<option value="{{ $mode }}" @selected(old('availability_mode', 'unlimited') === $mode)>{{ $modeLabels[$mode] }}</option>@endforeach</select>@error('availability_mode')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<x-input name="points_cost" type="number" min="0.0001" step="0.0001" label="Costo en puntos" :value="old('points_cost', '1')" required/>
<div x-show="mode === 'limited'" x-cloak><label for="stock_quantity" class="form-label">Cupo disponible<span class="text-red-500">*</span></label><input type="number" name="stock_quantity" id="stock_quantity" min="0.0001" step="0.0001" :value="old('stock_quantity')" class="form-input">@error('stock_quantity')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<div x-show="mode === 'product'" x-cloak><label for="product_id" class="form-label">Producto asociado<span class="text-red-500">*</span></label><select name="product_id" id="product_id" class="form-input"><option value="">Seleccione un producto</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((string) old('product_id') === (string) $product->id)>{{ $product->name }}</option>@endforeach</select>@error('product_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
<x-input name="description" label="Descripción (opcional)" :value="old('description')"/>
<input type="hidden" name="is_active" value="1"><div class="md:col-span-2"><button class="rounded-lg bg-amber-500 px-5 py-2.5 font-semibold text-black">Crear premio</button></div></form></x-card>
<div class="space-y-4">@forelse($rewards as $reward)<x-card><form method="POST" action="{{ route('loyalty.rewards.update', $reward) }}" x-data="{ mode: @js($reward->availability_mode) }" class="grid gap-3 md:grid-cols-6">@csrf @method('PUT')
<input name="name" value="{{ $reward->name }}" class="form-input"><select name="type" class="form-input">@foreach($types as $type)<option value="{{ $type }}" @selected($reward->type === $type)>{{ ['product' => 'Producto', 'discount' => 'Descuento', 'service' => 'Servicio', 'gift' => 'Regalo'][$type] }}</option>@endforeach</select><input name="points_cost" type="number" step="0.0001" value="{{ $reward->points_cost }}" class="form-input"><select name="availability_mode" x-model="mode" class="form-input">@foreach($modes as $mode)<option value="{{ $mode }}" @selected($reward->availability_mode === $mode)>{{ $modeLabels[$mode] }}</option>@endforeach</select>
<input x-show="mode === 'limited'" x-cloak name="stock_quantity" type="number" step="0.0001" min="0.0001" value="{{ $reward->stock_quantity }}" placeholder="Cupo" class="form-input">
<select x-show="mode === 'product'" x-cloak name="product_id" class="form-input"><option value="">Producto asociado</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($reward->product_id === $product->id)>{{ $product->name }}</option>@endforeach</select>
<input name="description" value="{{ $reward->description }}" class="form-input" placeholder="Descripción"><input type="hidden" name="is_active" value="{{ $reward->is_active ? 1 : 0 }}"><button class="rounded bg-slate-800 px-3 py-2 text-white">Guardar</button></form>
<form method="POST" action="{{ route('loyalty.rewards.toggle', $reward) }}" class="mt-3">@csrf @method('PATCH')<span class="mr-3 text-xs uppercase tracking-wide {{ $reward->is_active ? 'text-emerald-700' : 'text-slate-400' }}">{{ $reward->is_active ? 'Activo' : 'Inactivo' }}</span><button class="text-sm font-semibold {{ $reward->is_active ? 'text-red-600' : 'text-emerald-700' }}">{{ $reward->is_active ? 'Desactivar' : 'Activar' }}</button></form></x-card>@empty<p class="text-slate-500">No hay premios configurados.</p>@endforelse</div>{{ $rewards->links() }}
</div>
@endsection
