@extends('layouts.platform')
@section('title', 'Nueva empresa')
@section('content')
<div x-data="{ step: 1, branches: [{ name: '', code: '', phone: '', address: '' }] }" class="mx-auto max-w-5xl space-y-5" data-company-onboarding>
    <header><a href="{{ route('platform.index') }}" class="text-sm font-semibold text-amber-700">← Panel Maestro</a><h1 class="mt-2 text-2xl font-bold sm:text-3xl">Alta de nueva empresa</h1><p class="mt-2 text-sm text-slate-600">Complete los siete pasos. Nada se guarda hasta finalizar.</p></header>
    <ol class="grid grid-cols-4 gap-2 text-center text-xs font-bold sm:grid-cols-7" aria-label="Progreso del asistente">
        @foreach(['Empresa','Identidad','Sucursales','Administrador','Módulos','Configuración','Finalizar'] as $number => $label)<li class="rounded-xl border p-2" :class="step === {{ $number + 1 }} ? 'border-amber-500 bg-amber-50 text-amber-800' : 'border-slate-200 bg-white text-slate-500'"><span class="block">{{ $number + 1 }}</span><span class="hidden sm:block">{{ $label }}</span></li>@endforeach
    </ol>
    <form method="POST" action="{{ route('platform.companies.store') }}" enctype="multipart/form-data" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">@csrf
        <section x-show="step === 1" class="space-y-4"><h2 class="text-lg font-bold">1. Datos de empresa</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            <label class="text-sm font-semibold">Nombre comercial<input name="trade_name" value="{{ old('trade_name') }}" required class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><label class="text-sm font-semibold">Razón social<input name="legal_name" value="{{ old('legal_name') }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label>
            <label class="text-sm font-semibold">Tipo de identificación<select name="identification_type" class="mt-2 min-h-11 w-full rounded-xl border px-4"><option value="">Seleccione</option>@foreach(['01'=>'Física','02'=>'Jurídica','03'=>'DIMEX','04'=>'NITE','05'=>'Extranjera'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="text-sm font-semibold">Identificación<input name="identification_number" value="{{ old('identification_number') }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label>
        </div></section>
        <section x-cloak x-show="step === 2" class="space-y-4"><h2 class="text-lg font-bold">2. Identidad comercial y fiscal</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><label class="text-sm font-semibold">Logo<input type="file" name="logo" accept="image/*" class="mt-2 min-h-11 w-full rounded-xl border p-2"></label><label class="text-sm font-semibold">Correo comercial<input type="email" name="email" value="{{ old('email') }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><label class="text-sm font-semibold">Teléfono<input name="phone" value="{{ old('phone') }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><label class="text-sm font-semibold">Dirección<input name="address" value="{{ old('address') }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label></div></section>
        <section x-cloak x-show="step === 3" class="space-y-4"><div class="flex items-center justify-between"><h2 class="text-lg font-bold">3. Sucursales</h2><button type="button" @click="branches.push({name:'',code:'',phone:'',address:''})" class="min-h-11 rounded-xl border px-4 font-semibold">Agregar sucursal</button></div><template x-for="(branch,index) in branches" :key="index"><div class="grid grid-cols-1 gap-3 rounded-xl border p-4 md:grid-cols-2"><input :name="`branches[${index}][name]`" x-model="branch.name" required placeholder="Nombre" class="min-h-11 rounded-xl border px-4"><input :name="`branches[${index}][code]`" x-model="branch.code" required placeholder="Código único" class="min-h-11 rounded-xl border px-4"><input :name="`branches[${index}][phone]`" x-model="branch.phone" placeholder="Teléfono" class="min-h-11 rounded-xl border px-4"><div class="flex gap-2"><input :name="`branches[${index}][address]`" x-model="branch.address" placeholder="Dirección" class="min-h-11 min-w-0 flex-1 rounded-xl border px-4"><button x-show="branches.length > 1" type="button" @click="branches.splice(index,1)" class="min-h-11 rounded-xl border px-3">Quitar</button></div></div></template></section>
        <section x-cloak x-show="step === 4" class="space-y-4"><h2 class="text-lg font-bold">4. Administrador inicial</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><label class="text-sm font-semibold">Nombre<input name="administrator[name]" required class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><label class="text-sm font-semibold">Correo<input type="email" name="administrator[email]" required class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><label class="text-sm font-semibold">Teléfono<input name="administrator[phone]" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><span></span><label class="text-sm font-semibold">Contraseña<input type="password" name="administrator[password]" required class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><label class="text-sm font-semibold">Confirmación<input type="password" name="administrator[password_confirmation]" required class="mt-2 min-h-11 w-full rounded-xl border px-4"></label></div></section>
        <section x-cloak x-show="step === 5" class="space-y-4"><h2 class="text-lg font-bold">5. Módulos iniciales</h2><p class="text-sm text-slate-600">El administrador recibirá permisos, pero solo podrá usar los módulos contratados.</p><div class="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">@foreach($moduleCatalog as $key=>$module)<label class="flex min-h-14 items-center gap-3 rounded-xl border p-4 text-sm font-semibold"><input type="checkbox" name="modules[]" value="{{ $key }}" checked class="h-5 w-5 rounded">{{ $module['label'] }}</label>@endforeach</div></section>
        <section x-cloak x-show="step === 6" class="space-y-4"><h2 class="text-lg font-bold">6. Configuración básica</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><label class="text-sm font-semibold">Moneda<select name="currency" class="mt-2 min-h-11 w-full rounded-xl border px-4"><option value="CRC">CRC · Colón</option><option value="USD">USD · Dólar</option></select></label><label class="text-sm font-semibold">Zona horaria<input name="timezone" value="America/Costa_Rica" required class="mt-2 min-h-11 w-full rounded-xl border px-4"></label></div><p class="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">También se crearán métodos de pago, configuración de caja y denominaciones iniciales mediante los servicios estándar.</p></section>
        <section x-cloak x-show="step === 7" class="space-y-4"><h2 class="text-lg font-bold">7. Finalización</h2><p class="text-sm leading-6 text-slate-600">Revise los pasos anteriores. Al finalizar se crearán empresa, sucursales, administrador, rol, módulos y configuración en una sola operación.</p><button class="min-h-11 w-full rounded-xl bg-amber-500 px-5 font-bold text-slate-950">Crear empresa y finalizar</button></section>
        <div class="mt-7 flex justify-between gap-3 border-t pt-5"><button x-show="step > 1" type="button" @click="step--" class="min-h-11 rounded-xl border px-5 font-semibold">Anterior</button><span x-show="step === 1"></span><button x-show="step < 7" type="button" @click="step++" class="min-h-11 rounded-xl bg-slate-950 px-5 font-semibold text-white">Continuar</button></div>
    </form>
</div>
@endsection
