@extends('layouts.platform')
@section('title', $company->trade_name)
@section('content')
<div class="space-y-6" data-platform-company="{{ $company->id }}">
    <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('platform.index') }}" class="text-sm font-semibold text-amber-700">← Empresas</a><h1 class="mt-2 text-2xl font-bold sm:text-3xl">{{ $company->trade_name }}</h1><p class="mt-1 text-sm text-slate-500">Tenant #{{ $company->id }} · supervisión contractual</p></div><span class="rounded-full bg-amber-100 px-3 py-2 text-sm font-bold text-amber-800">{{ ucfirst($company->license->status) }}</span></header>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-4"><div><h2 class="font-bold">Datos del tenant</h2><p class="mt-1 text-sm text-slate-500">Solo lectura. El propietario administra estos datos desde su onboarding/configuración.</p></div><span class="rounded-full px-3 py-1 text-xs font-bold {{ $company->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-600' }}">{{ $company->is_active ? 'Activa' : 'Inactiva' }}</span></div>
        <dl class="mt-4 grid grid-cols-1 gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3">@foreach(['legal_name'=>'Razón social','identification_number'=>'Identificación','email'=>'Correo empresarial','phone'=>'Teléfono','currency'=>'Moneda','timezone'=>'Zona horaria'] as $field=>$label)<div><dt class="text-slate-500">{{ $label }}</dt><dd class="mt-1 font-semibold">{{ $company->$field ?: 'Sin completar' }}</dd></div>@endforeach<div><dt class="text-slate-500">Propietario tenant</dt><dd class="mt-1 font-semibold">{{ $company->owner?->name ?? 'Sin asignar' }}<br><span class="font-normal">{{ $company->owner?->email }}</span></dd></div></dl>
    </section>

    <section class="grid grid-cols-1 gap-4 lg:grid-cols-2"><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Sucursales · solo lectura</h2><div class="mt-4 space-y-3">@forelse($company->branches as $branch)<div class="rounded-xl border p-4"><strong>{{ $branch->name }}</strong><span class="ml-2 text-sm text-slate-500">{{ $branch->code }} · {{ $branch->is_active ? 'Activa' : 'Inactiva' }}</span></div>@empty<p class="text-sm text-slate-500">El propietario aún no completó su primera sucursal.</p>@endforelse</div></article>
        <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Usuarios · solo lectura</h2><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="p-3">Usuario</th><th class="p-3">Rol</th><th class="p-3">Estado</th></tr></thead><tbody>@foreach($company->users as $user)<tr class="border-t"><td class="p-3"><strong>{{ $user->name }}</strong><br>{{ $user->email }}</td><td class="p-3">{{ $company->roles->firstWhere('id', $user->pivot->role_id)?->name ?: 'Sin rol' }}</td><td class="p-3">{{ $user->is_active ? 'Activo' : 'Inactivo' }}</td></tr>@endforeach</tbody></table></div></article>
    </section>

    <form method="POST" action="{{ route('platform.licenses.update', $company) }}" class="rounded-2xl border border-amber-200 bg-white p-5 shadow-sm">@csrf @method('PATCH')
        <h2 class="font-bold">Contrato efectivo · {{ ucfirst($company->license->status) }}</h2><p class="mt-2 text-sm text-slate-600">La plantilla propone valores. Guardar overrides modifica solo este tenant.</p>
        <div class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            <label class="text-sm font-semibold">Plantilla comercial<select name="license_plan_id" class="mt-2 min-h-11 w-full rounded-xl border px-4"><option value="">Contrato sin plantilla</option>@foreach($licensePlans as $plan)<option value="{{ $plan->id }}" @selected($company->license->license_plan_id === $plan->id)>{{ $plan->name }}</option>@endforeach</select></label>
            <label class="flex min-h-11 items-center gap-3 self-end text-sm font-semibold"><input type="checkbox" name="apply_plan" value="1" class="h-5 w-5"> Reaplicar valores de la plantilla</label>
            <label class="text-sm font-semibold">Estado<select name="status" class="mt-2 min-h-11 w-full rounded-xl border px-4">@foreach(\App\Models\CompanyLicense::STATUSES as $status)<option value="{{ $status }}" @selected($company->license->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Referencia contractual<input name="plan" required value="{{ $company->license->plan }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label>
            @foreach(['starts_at'=>'Inicio','expires_at'=>'Vencimiento','next_renewal_at'=>'Próxima renovación','grace_until'=>'Fin de gracia'] as $field=>$label)<label class="text-sm font-semibold">{{ $label }}<input type="datetime-local" name="{{ $field }}" value="{{ $company->license->$field?->format('Y-m-d\TH:i') }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label>@endforeach
            <label class="text-sm font-semibold">Límite usuarios<input type="number" min="1" name="user_limit" value="{{ $company->license->user_limit }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label><label class="text-sm font-semibold">Límite sucursales<input type="number" min="1" name="branch_limit" value="{{ $company->license->branch_limit }}" class="mt-2 min-h-11 w-full rounded-xl border px-4"></label>
        </div><label class="mt-4 block text-sm font-semibold">Nota de auditoría<textarea name="notes" class="mt-2 w-full rounded-xl border p-4">{{ $company->license->notes }}</textarea></label>
        <div class="mt-5 flex flex-wrap gap-3"><button name="action" value="update" class="min-h-11 rounded-xl bg-amber-500 px-5 font-bold">Guardar contrato</button><button name="action" value="activate" class="min-h-11 rounded-xl border px-5 font-semibold">Activar</button><button name="action" value="renew" class="min-h-11 rounded-xl border border-emerald-300 bg-emerald-50 px-5 font-semibold text-emerald-800">Renovar / extender</button><button name="action" value="suspend" class="min-h-11 rounded-xl border px-5 font-semibold">Suspender</button><button name="action" value="reactivate" class="min-h-11 rounded-xl border px-5 font-semibold">Reactivar</button><button name="action" value="cancel" class="min-h-11 rounded-xl border border-red-300 px-5 font-semibold text-red-700">Cancelar</button></div>
        <div class="mt-6 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="p-3">Fecha</th><th class="p-3">Acción/cambio</th><th class="p-3">Actor</th></tr></thead><tbody>@forelse($company->license->events as $event)<tr class="border-t"><td class="p-3">{{ $event->created_at->format('d/m/Y H:i') }}</td><td class="p-3">{{ $event->action }} · {{ $event->from_status ?: '—' }} → {{ $event->to_status }} @if($event->changes)<span class="block text-xs text-slate-500">{{ implode(', ', array_keys($event->changes)) }}</span>@endif</td><td class="p-3">{{ $event->actor?->email ?: 'Sistema' }}</td></tr>@empty<tr><td colspan="3" class="p-3">Sin cambios.</td></tr>@endforelse</tbody></table></div>
    </form>

    <form method="POST" action="{{ route('platform.modules.update', $company) }}" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">@csrf @method('PATCH')<h2 class="font-bold">Módulos del contrato efectivo</h2><div class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">@foreach($moduleCatalog as $key=>$module)<label class="flex min-h-14 items-center gap-3 rounded-xl border p-4 text-sm font-semibold"><input type="checkbox" name="modules[]" value="{{ $key }}" @checked($company->isModuleEnabled($key)) class="h-5 w-5"> {{ $module['label'] }}</label>@endforeach</div><button class="mt-5 min-h-11 rounded-xl bg-slate-950 px-5 font-semibold text-white">Guardar módulos</button></form>
</div>
@endsection
